if ('serviceWorker' in navigator) window.addEventListener('load', ()=> navigator.serviceWorker.register('./sw.js'));
const loginForm=document.getElementById('loginForm'); const passApp=document.getElementById('passApp'); const loginMsg=document.getElementById('loginMsg'); const moduleCard=document.getElementById('moduleCard'); const loginCard=document.getElementById('loginCard'); const passWrite=document.getElementById('passWrite'); const btnSetWrite=document.getElementById('btnSetWrite'); const writeState=document.getElementById('writeState');
function setLoggedIn(inState){ if(!moduleCard||!loginCard) return; if(inState){ moduleCard.classList.remove('hidden'); loginCard.classList.add('hidden'); prefillURLs(); } else { moduleCard.classList.add('hidden'); loginCard.classList.remove('hidden'); } }
async function apiPing(p){ try{ const r=await apiPost('pingApp', {}, p); return r.ok===true; }catch(_){ return false; } }
function prefillURLs(){ ['TAVI','TEER','LAAC'].forEach(k=>{ const el=document.getElementById('url'+k); if(!el) return; const stored=localStorage.getItem('URL_'+k) || window.API_DEFAULTS[k] || ''; el.value=stored; }); }
function setModule(k){ sessionStorage.setItem('MODULE', k); const url = localStorage.getItem('URL_'+k) || window.API_DEFAULTS[k] || ''; sessionStorage.setItem('API_URL', url); }
function saveURL(k){ const el=document.getElementById('url'+k); if(!el) return; localStorage.setItem('URL_'+k, el.value.trim()); alert('URL '+k+' salvato'); }
(async ()=>{ const p=sessionStorage.getItem('PASS_APP'); if(p && await apiPing(p)) setLoggedIn(true); })();
loginForm?.addEventListener('submit', async (e)=>{ e.preventDefault(); const p=passApp.value.trim(); loginMsg.textContent='Verifica…'; const ok=await apiPing(p); if(ok){ sessionStorage.setItem('PASS_APP', p); setLoggedIn(true); loginMsg.textContent='OK'; } else { sessionStorage.removeItem('PASS_APP'); loginMsg.textContent='Password errata.'; } });
btnSetWrite?.addEventListener('click', async ()=>{ const pw=passWrite.value.trim(); const r=await apiPost('pingWrite', {}, sessionStorage.getItem('PASS_APP'), pw); if(r.ok){ sessionStorage.setItem('PASS_WRITE', pw); writeState.textContent='SBLOCCATE'; writeState.classList.remove('warn'); writeState.classList.add('ok'); } else { sessionStorage.removeItem('PASS_WRITE'); writeState.textContent='BLOCCATE'; writeState.classList.add('warn'); } });